name: Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: vars.PROJECT_NUMBER != ''
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.6.1
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/${{ vars.PROJECT_NUMBER }}
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}